Use `--force` option for brakeman on CI
Because brakeman fails with the error below if Rails application is missing.

```
 Running brakeman with reviewdog 🐶 ...
  Please supply the path to a Rails application (looking in /home/runner/work/action-brakeman/action-brakeman).
    Use `--force` to run a scan anyway.
  Error: Process completed with exit code 4.
```


https://github.com/reviewdog/action-brakeman/runs/4775703532?check_suite_focus=true